
#include "responseHandler.h"


ResponseHandler::ResponseHandler(EncryptionHandler* _eh, TransferInfo* ti, bool* validCrc){
    eh = _eh;
    _transferInfo = ti;
    _validCrc = validCrc;
}

//Handles response selection according to predefined reponse codes
bool ResponseHandler::responseSelector(responsePacket* responsePacket, uint16_t code) {
    
    switch(code){
        case (responseCodes::GENERAL_ERR): std::cerr << "Client: Server responded with an error\n"; return true;
        case(responseCodes::REG_FAILED): return true;
        case(responseCodes::REG_SUCCESSFUL): return createNewClientFile(responsePacket->payload);
        case(responseCodes::IN_PUBLIC_OUT_CRYPTED): return recieveAesKey(responsePacket->payload);
        case(responseCodes::VALID_CRC_FILE): return checkSum(responsePacket->payload);
        case(responseCodes::OK_RECONN_OUT_AES): std::cout << "Client: Client signed in successfully!\n"; return recieveAesKey(responsePacket->payload);
        case(responseCodes::RECONNECT_FAILED): std::cout << "Client: Could not sign in successfully - Registering as a new client\n"; return true;
        case(responseCodes::MSG_RECIEVED):return endMessage();
        default: return false;
    }
 } 

/******************************** Response Functions ********************************
* Each response function parses a 'responsePacket' struct that was packed by the connection handler class with data recieved by the server.
* Each function takes care of a single clinet response for the server's response according to predefined protocol reponse codes.
* Each responsePacket struct contains a protocal defined header fields that includes: Version, response code and payload size.
* Each responsePacket struct contains a payload suitable for it's response.
* Payload size and content varies for each response.
*/


/**
 * Response Code: 1600 
 * Handles new client file creation (me.info and priv.key)
 * me.info file contains: null terminated username,UUID in Hex base,RSA private key generated by the client in 64 base
 * key.priv file contaions: RSA private key
 */
bool ResponseHandler::createNewClientFile(std::vector<unsigned char> payload){
    std::ifstream key;
    std::ofstream file;
    std::string hexUuid;
    
    if (!eh->saveEncodedPrivateKey())
        return false;

    if(std::filesystem::exists("me.info")){
        std::cout<<"Client error: client's info file already exists, cannot register as a new client.\n";
        return false;
    }
        
    key.open("key.priv");
    if(!key.is_open()){
        std::cout<<"Could not create client's info file - connection is terminated\n";
        return false;
    }
    file.open("me.info");
    if (!file.is_open()) {
        std::cout << "Could not read private key - connection is terminated\n";
        return false;
    }

    hexUuid = toHex(payload);
    file<< _transferInfo->getUserName() <<"\n"<< hexUuid << "\n" << key.rdbuf();
    key.close();
    file.close();
    std::cout << "Client: Client registration process completed successfully!\n";
    return true;      
}

/**
 * Response Code: 1602,1605
 * Handles Handles receiving and decrypting an AES key.
 * Dencrypts with the private key the AES key that the sever encrypted with the client's public key
 * Saves the key for symetric encryption 
 */
bool ResponseHandler::recieveAesKey(std::vector<unsigned char> payload){
    try {
        size_t keysize = payload.size() - UID_SIZE;
        if (keysize <= 0)
            throw std::runtime_error("Encrypted AES key from the server isn't valid. Expected size: " + std::to_string(AES_KEY_SIZE) + ", but got: " + std::to_string(keysize));
        return eh->decryptAESKey(&payload[UID_SIZE], keysize);
    }
    catch (std::exception& e) {
        std::cerr <<"Client error During AES decryption: "<< e.what()+'\n';
        return false;
    }
}
     
/**
 * Response Code: 1603
 * Handles CRC calculation and comparison.
 * Calculates CRC to the uploaded file, and comapres it with the CRC that the server computed.
 * Returns true if equal,else false
 */

bool ResponseHandler::checkSum(std::vector<unsigned char>& payload) {
    unsigned long crcClient = readfile(_transferInfo->getPath());
    unsigned long crcServer = 0;
    bool crcValue;
    std::vector<unsigned char> crc(payload.end() - sizeof(uint32_t), payload.end());
    std::memcpy(&crcServer, crc.data(), sizeof(uint32_t));
    crcValue = crcClient == crcServer;
    *_validCrc = crcValue;
    crcValue ? 
        std::cout << "Client: Verifying checksum for the encrypted file...\n":
        std::cerr << "Client Error: Checksum verification failed!\n";
    return true;
    
}

/**
 * Response Code: 1604
 * Handles connection ending prompt 
 */

bool ResponseHandler::endMessage() {
    !*_validCrc ? 
        std::cerr << "Client Error: Checksum verification failed for the 3rd time! Terminating proccess.\n\n" :
        std::cout << "Client: File was uploaded successfully to the server. End of proccess\n\n";
    return true;
}

// converts binary strings to hex strings 
std::string ResponseHandler::toHex(const std::vector<unsigned char>& payload) {
    std::ostringstream oss;
    for (const auto& byte : payload)
        oss << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(byte);
    std::dec;
    return oss.str();
}
