
##### protocol related
HEADER_SIZE = 23
CHUNK_SIZE = 1024
USER_ID_SIZE = 16
VERSION = 3
DEFUALT_PORT = 1256
HOST = '127.0.0.1'
FILE_NAME_SIZE = 255
PAYLOAD_SIZE_INDEX = 3
UINT32_T = 4
UINT16_T = 2
UINT8_T = 1

##### Server response codes
INIT_REGISTRATION_SUCC = 1600
REGISTRATION_FAIL = 1601
IN_PUBLIC_KEY_OUT_AES = 1602
VALID_FILE_CRC = 1603
FILE_APPROVAL = 1604
RECCONECT_APPROVED = 1605
RECCONET_DENIED = 1606
GENERAL_ERROR = 1607

#### Client request codes
REGISTER = 825
S_PUBLIC_KEY = 826
RECONNECT = 827
SEND_FILE = 828
VALID_CRC = 900
N_VALID_CRC = 901
EXIT_CRC = 902

##### Encryption
AES_KEY_SIZE = 32
PUBLIC_KEY = 160
CONTENT_INDEX =  267
NAME_INDEX = 12
IV = b'\x00' * 16

##### Database fields and values
TRUE = 1
FALSE = 0
DB_NAME = "defensive.db"
UUID = 'uuid'
FILE_NAME_FIELD = 'file_name'
PATH_NAME_FIELD = 'path_name'
VERIFIED_FIELD = 'verified'
USER_NAME_FIELD = 'user_name'
PUBLIC_KEY_FIELD = 'public_key'
LAST_SEEN_FIELD = 'last_seen'
AES_KEY_FIELD = 'aes_key'
BACKUP_PATH_NAME = 'backupsvr'
CLIENTS_TABLE = 'clients'
FILES_TABLE = 'files'

